/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Gen_relojes_synth.v:1" *)
module Gen_relojes_synth(clk_out, clk_in);
  (* src = "Gen_relojes_synth.v:7" *)
  wire _00_;
  (* src = "Gen_relojes_synth.v:7" *)
  wire [31:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "Gen_relojes_synth.v:3" *)
  input clk_in;
  (* src = "Gen_relojes_synth.v:2" *)
  output clk_out;
  (* init = 32'd0 *)
  (* src = "Gen_relojes_synth.v:4" *)
  wire [31:0] counter;
  NOR _32_ (
    .A(counter[16]),
    .B(counter[18]),
    .Y(_02_)
  );
  NOR _33_ (
    .A(counter[20]),
    .B(counter[23]),
    .Y(_03_)
  );
  NAND _34_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  NOR _35_ (
    .A(counter[8]),
    .B(counter[10]),
    .Y(_05_)
  );
  NOR _36_ (
    .A(counter[12]),
    .B(counter[14]),
    .Y(_06_)
  );
  NAND _37_ (
    .A(_05_),
    .B(_06_),
    .Y(_07_)
  );
  NOR _38_ (
    .A(_04_),
    .B(_07_),
    .Y(_08_)
  );
  NOR _39_ (
    .A(counter[29]),
    .B(counter[28]),
    .Y(_09_)
  );
  NOR _40_ (
    .A(counter[30]),
    .B(counter[31]),
    .Y(_10_)
  );
  NAND _41_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _42_ (
    .A(counter[22]),
    .B(counter[25]),
    .Y(_12_)
  );
  NOR _43_ (
    .A(counter[24]),
    .B(counter[26]),
    .Y(_13_)
  );
  NAND _44_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _45_ (
    .A(_11_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _46_ (
    .A(_08_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _47_ (
    .A(counter[9]),
    .B(counter[11]),
    .Y(_17_)
  );
  NOR _48_ (
    .A(counter[13]),
    .B(counter[15]),
    .Y(_18_)
  );
  NAND _49_ (
    .A(_17_),
    .B(_18_),
    .Y(_19_)
  );
  NOR _50_ (
    .A(counter[1]),
    .B(counter[3]),
    .Y(_20_)
  );
  NOR _51_ (
    .A(counter[5]),
    .B(counter[7]),
    .Y(_21_)
  );
  NAND _52_ (
    .A(_20_),
    .B(_21_),
    .Y(_22_)
  );
  NOR _53_ (
    .A(_19_),
    .B(_22_),
    .Y(_23_)
  );
  NOR _54_ (
    .A(counter[0]),
    .B(counter[2]),
    .Y(_24_)
  );
  NOR _55_ (
    .A(counter[4]),
    .B(counter[6]),
    .Y(_25_)
  );
  NAND _56_ (
    .A(_24_),
    .B(_25_),
    .Y(_26_)
  );
  NOR _57_ (
    .A(counter[17]),
    .B(counter[19]),
    .Y(_27_)
  );
  NOR _58_ (
    .A(counter[21]),
    .B(counter[27]),
    .Y(_28_)
  );
  NAND _59_ (
    .A(_27_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _60_ (
    .A(_26_),
    .B(_29_),
    .Y(_30_)
  );
  NAND _61_ (
    .A(_23_),
    .B(_30_),
    .Y(_31_)
  );
  NOR _62_ (
    .A(_16_),
    .B(_31_),
    .Y(_01_[0])
  );
  NOR _63_ (
    .A(_16_),
    .B(_31_),
    .Y(_00_)
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _64_ (
    .C(clk_in),
    .D(_00_),
    .Q(clk_out)
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _65_ (
    .C(clk_in),
    .D(_01_[0]),
    .Q(counter[0])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _66_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[1])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _67_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[2])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _68_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[3])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _69_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[4])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _70_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[5])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _71_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[6])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _72_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[7])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _73_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[8])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _74_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[9])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _75_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[10])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _76_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[11])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _77_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[12])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _78_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[13])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _79_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[14])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _80_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[15])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _81_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[16])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _82_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[17])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _83_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[18])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _84_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[19])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _85_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[20])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _86_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[21])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _87_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[22])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _88_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[23])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _89_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[24])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _90_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[25])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _91_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[26])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _92_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[27])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _93_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[28])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _94_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[29])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _95_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[30])
  );
  (* src = "Gen_relojes_synth.v:7" *)
  DFF _96_ (
    .C(clk_in),
    .D(1'h0),
    .Q(counter[31])
  );
  assign _01_[31:1] = 31'h00000000;
endmodule
