/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */
`include "cmos_cells.v"
(* top =  1  *)
(* src = "serial_paralelo.v:1" *)
module estructural(data_in, data_out, clk_32f, clk_4f, active, valid_out, BC_counter);
  (* src = "serial_paralelo.v:8" *)
  output [2:0] BC_counter;
  (* src = "serial_paralelo.v:6" *)
  output active;
  (* src = "serial_paralelo.v:11" *)
  wire [0:7] bus0;
  (* src = "serial_paralelo.v:4" *)
  input clk_32f;
  (* src = "serial_paralelo.v:5" *)
  input clk_4f;
  (* src = "serial_paralelo.v:2" *)
  input data_in;
  (* src = "serial_paralelo.v:3" *)
  output [7:0] data_out;
  (* src = "serial_paralelo.v:7" *)
  input valid_out;
  DFF _0_ (
    .C(clk_4f),
    .D(bus0[7]),
    .Q(data_out[0])
  );
  DFF _1_ (
    .C(clk_4f),
    .D(bus0[6]),
    .Q(data_out[1])
  );
  DFF _2_ (
    .C(clk_4f),
    .D(bus0[5]),
    .Q(data_out[2])
  );
  DFF _3_ (
    .C(clk_4f),
    .D(bus0[4]),
    .Q(data_out[3])
  );
  DFF _4_ (
    .C(clk_4f),
    .D(bus0[3]),
    .Q(data_out[4])
  );
  DFF _5_ (
    .C(clk_4f),
    .D(bus0[2]),
    .Q(data_out[5])
  );
  DFF _6_ (
    .C(clk_4f),
    .D(bus0[1]),
    .Q(data_out[6])
  );
  DFF _7_ (
    .C(clk_4f),
    .D(bus0[0]),
    .Q(data_out[7])
  );
  DFF _8_ (
    .C(clk_32f),
    .D(data_in),
    .Q(bus0[0])
  );
  assign BC_counter = 3'b000;
  assign active = 1'b0;
endmodule
