/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth.v:1" *)
module synth(data_out, reset_L, lane0, lane1, valid_0, valid_1, valid_out, clk_2f, clk_f);
  (* src = "synth.v:12" *)
  wire [31:0] _000_;
  (* src = "synth.v:12" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  (* src = "synth.v:9" *)
  input clk_2f;
  (* src = "synth.v:10" *)
  input clk_f;
  (* src = "synth.v:2" *)
  output [31:0] data_out;
  (* src = "synth.v:4" *)
  input [31:0] lane0;
  (* src = "synth.v:5" *)
  input [31:0] lane1;
  (* src = "synth.v:3" *)
  input reset_L;
  (* src = "synth.v:11" *)
  wire selector;
  (* src = "synth.v:6" *)
  input valid_0;
  (* src = "synth.v:7" *)
  input valid_1;
  (* src = "synth.v:8" *)
  output valid_out;
  NOT _131_ (
    .A(reset_L),
    .Y(_002_)
  );
  NOT _132_ (
    .A(lane1[0]),
    .Y(_003_)
  );
  NOT _133_ (
    .A(lane1[1]),
    .Y(_004_)
  );
  NOT _134_ (
    .A(lane1[2]),
    .Y(_005_)
  );
  NOT _135_ (
    .A(lane1[3]),
    .Y(_006_)
  );
  NOT _136_ (
    .A(lane1[4]),
    .Y(_007_)
  );
  NOT _137_ (
    .A(lane1[5]),
    .Y(_008_)
  );
  NOT _138_ (
    .A(lane1[6]),
    .Y(_009_)
  );
  NOT _139_ (
    .A(lane1[7]),
    .Y(_010_)
  );
  NOT _140_ (
    .A(lane1[8]),
    .Y(_011_)
  );
  NOT _141_ (
    .A(lane1[9]),
    .Y(_012_)
  );
  NOT _142_ (
    .A(lane1[10]),
    .Y(_013_)
  );
  NOT _143_ (
    .A(lane1[11]),
    .Y(_014_)
  );
  NOT _144_ (
    .A(lane1[12]),
    .Y(_015_)
  );
  NOT _145_ (
    .A(lane1[13]),
    .Y(_016_)
  );
  NOT _146_ (
    .A(lane1[14]),
    .Y(_017_)
  );
  NOT _147_ (
    .A(lane1[15]),
    .Y(_018_)
  );
  NOT _148_ (
    .A(lane1[16]),
    .Y(_019_)
  );
  NOT _149_ (
    .A(lane1[17]),
    .Y(_020_)
  );
  NOT _150_ (
    .A(lane1[18]),
    .Y(_021_)
  );
  NOT _151_ (
    .A(lane1[19]),
    .Y(_022_)
  );
  NOT _152_ (
    .A(lane1[20]),
    .Y(_023_)
  );
  NOT _153_ (
    .A(lane1[21]),
    .Y(_024_)
  );
  NOT _154_ (
    .A(lane1[22]),
    .Y(_025_)
  );
  NOT _155_ (
    .A(lane1[23]),
    .Y(_026_)
  );
  NOT _156_ (
    .A(lane1[24]),
    .Y(_027_)
  );
  NOT _157_ (
    .A(lane1[25]),
    .Y(_028_)
  );
  NOT _158_ (
    .A(lane1[26]),
    .Y(_029_)
  );
  NOT _159_ (
    .A(lane1[27]),
    .Y(_030_)
  );
  NOT _160_ (
    .A(lane1[28]),
    .Y(_031_)
  );
  NOT _161_ (
    .A(lane1[29]),
    .Y(_032_)
  );
  NOT _162_ (
    .A(lane1[30]),
    .Y(_033_)
  );
  NOT _163_ (
    .A(lane1[31]),
    .Y(_034_)
  );
  NOR _164_ (
    .A(selector),
    .B(lane0[5]),
    .Y(_035_)
  );
  NOR _165_ (
    .A(_002_),
    .B(selector),
    .Y(_001_)
  );
  NAND _166_ (
    .A(selector),
    .B(_008_),
    .Y(_036_)
  );
  NAND _167_ (
    .A(reset_L),
    .B(_036_),
    .Y(_037_)
  );
  NOR _168_ (
    .A(_035_),
    .B(_037_),
    .Y(_000_[5])
  );
  NOR _169_ (
    .A(selector),
    .B(lane0[6]),
    .Y(_038_)
  );
  NAND _170_ (
    .A(selector),
    .B(_009_),
    .Y(_039_)
  );
  NAND _171_ (
    .A(reset_L),
    .B(_039_),
    .Y(_040_)
  );
  NOR _172_ (
    .A(_038_),
    .B(_040_),
    .Y(_000_[6])
  );
  NOR _173_ (
    .A(selector),
    .B(lane0[7]),
    .Y(_041_)
  );
  NAND _174_ (
    .A(selector),
    .B(_010_),
    .Y(_042_)
  );
  NAND _175_ (
    .A(reset_L),
    .B(_042_),
    .Y(_043_)
  );
  NOR _176_ (
    .A(_041_),
    .B(_043_),
    .Y(_000_[7])
  );
  NOR _177_ (
    .A(selector),
    .B(lane0[8]),
    .Y(_044_)
  );
  NAND _178_ (
    .A(selector),
    .B(_011_),
    .Y(_045_)
  );
  NAND _179_ (
    .A(reset_L),
    .B(_045_),
    .Y(_046_)
  );
  NOR _180_ (
    .A(_044_),
    .B(_046_),
    .Y(_000_[8])
  );
  NOR _181_ (
    .A(selector),
    .B(lane0[9]),
    .Y(_047_)
  );
  NAND _182_ (
    .A(selector),
    .B(_012_),
    .Y(_048_)
  );
  NAND _183_ (
    .A(reset_L),
    .B(_048_),
    .Y(_049_)
  );
  NOR _184_ (
    .A(_047_),
    .B(_049_),
    .Y(_000_[9])
  );
  NOR _185_ (
    .A(selector),
    .B(lane0[10]),
    .Y(_050_)
  );
  NAND _186_ (
    .A(selector),
    .B(_013_),
    .Y(_051_)
  );
  NAND _187_ (
    .A(reset_L),
    .B(_051_),
    .Y(_052_)
  );
  NOR _188_ (
    .A(_050_),
    .B(_052_),
    .Y(_000_[10])
  );
  NOR _189_ (
    .A(selector),
    .B(lane0[11]),
    .Y(_053_)
  );
  NAND _190_ (
    .A(selector),
    .B(_014_),
    .Y(_054_)
  );
  NAND _191_ (
    .A(reset_L),
    .B(_054_),
    .Y(_055_)
  );
  NOR _192_ (
    .A(_053_),
    .B(_055_),
    .Y(_000_[11])
  );
  NOR _193_ (
    .A(selector),
    .B(lane0[12]),
    .Y(_056_)
  );
  NAND _194_ (
    .A(selector),
    .B(_015_),
    .Y(_057_)
  );
  NAND _195_ (
    .A(reset_L),
    .B(_057_),
    .Y(_058_)
  );
  NOR _196_ (
    .A(_056_),
    .B(_058_),
    .Y(_000_[12])
  );
  NOR _197_ (
    .A(selector),
    .B(lane0[13]),
    .Y(_059_)
  );
  NAND _198_ (
    .A(selector),
    .B(_016_),
    .Y(_060_)
  );
  NAND _199_ (
    .A(reset_L),
    .B(_060_),
    .Y(_061_)
  );
  NOR _200_ (
    .A(_059_),
    .B(_061_),
    .Y(_000_[13])
  );
  NOR _201_ (
    .A(selector),
    .B(lane0[14]),
    .Y(_062_)
  );
  NAND _202_ (
    .A(selector),
    .B(_017_),
    .Y(_063_)
  );
  NAND _203_ (
    .A(reset_L),
    .B(_063_),
    .Y(_064_)
  );
  NOR _204_ (
    .A(_062_),
    .B(_064_),
    .Y(_000_[14])
  );
  NOR _205_ (
    .A(selector),
    .B(lane0[15]),
    .Y(_065_)
  );
  NAND _206_ (
    .A(selector),
    .B(_018_),
    .Y(_066_)
  );
  NAND _207_ (
    .A(reset_L),
    .B(_066_),
    .Y(_067_)
  );
  NOR _208_ (
    .A(_065_),
    .B(_067_),
    .Y(_000_[15])
  );
  NOR _209_ (
    .A(selector),
    .B(lane0[16]),
    .Y(_068_)
  );
  NAND _210_ (
    .A(selector),
    .B(_019_),
    .Y(_069_)
  );
  NAND _211_ (
    .A(reset_L),
    .B(_069_),
    .Y(_070_)
  );
  NOR _212_ (
    .A(_068_),
    .B(_070_),
    .Y(_000_[16])
  );
  NOR _213_ (
    .A(selector),
    .B(lane0[17]),
    .Y(_071_)
  );
  NAND _214_ (
    .A(selector),
    .B(_020_),
    .Y(_072_)
  );
  NAND _215_ (
    .A(reset_L),
    .B(_072_),
    .Y(_073_)
  );
  NOR _216_ (
    .A(_071_),
    .B(_073_),
    .Y(_000_[17])
  );
  NOR _217_ (
    .A(selector),
    .B(lane0[18]),
    .Y(_074_)
  );
  NAND _218_ (
    .A(selector),
    .B(_021_),
    .Y(_075_)
  );
  NAND _219_ (
    .A(reset_L),
    .B(_075_),
    .Y(_076_)
  );
  NOR _220_ (
    .A(_074_),
    .B(_076_),
    .Y(_000_[18])
  );
  NOR _221_ (
    .A(selector),
    .B(lane0[19]),
    .Y(_077_)
  );
  NAND _222_ (
    .A(selector),
    .B(_022_),
    .Y(_078_)
  );
  NAND _223_ (
    .A(reset_L),
    .B(_078_),
    .Y(_079_)
  );
  NOR _224_ (
    .A(_077_),
    .B(_079_),
    .Y(_000_[19])
  );
  NOR _225_ (
    .A(selector),
    .B(lane0[20]),
    .Y(_080_)
  );
  NAND _226_ (
    .A(selector),
    .B(_023_),
    .Y(_081_)
  );
  NAND _227_ (
    .A(reset_L),
    .B(_081_),
    .Y(_082_)
  );
  NOR _228_ (
    .A(_080_),
    .B(_082_),
    .Y(_000_[20])
  );
  NOR _229_ (
    .A(selector),
    .B(lane0[21]),
    .Y(_083_)
  );
  NAND _230_ (
    .A(selector),
    .B(_024_),
    .Y(_084_)
  );
  NAND _231_ (
    .A(reset_L),
    .B(_084_),
    .Y(_085_)
  );
  NOR _232_ (
    .A(_083_),
    .B(_085_),
    .Y(_000_[21])
  );
  NOR _233_ (
    .A(selector),
    .B(lane0[22]),
    .Y(_086_)
  );
  NAND _234_ (
    .A(selector),
    .B(_025_),
    .Y(_087_)
  );
  NAND _235_ (
    .A(reset_L),
    .B(_087_),
    .Y(_088_)
  );
  NOR _236_ (
    .A(_086_),
    .B(_088_),
    .Y(_000_[22])
  );
  NOR _237_ (
    .A(selector),
    .B(lane0[23]),
    .Y(_089_)
  );
  NAND _238_ (
    .A(selector),
    .B(_026_),
    .Y(_090_)
  );
  NAND _239_ (
    .A(reset_L),
    .B(_090_),
    .Y(_091_)
  );
  NOR _240_ (
    .A(_089_),
    .B(_091_),
    .Y(_000_[23])
  );
  NOR _241_ (
    .A(selector),
    .B(lane0[24]),
    .Y(_092_)
  );
  NAND _242_ (
    .A(selector),
    .B(_027_),
    .Y(_093_)
  );
  NAND _243_ (
    .A(reset_L),
    .B(_093_),
    .Y(_094_)
  );
  NOR _244_ (
    .A(_092_),
    .B(_094_),
    .Y(_000_[24])
  );
  NOR _245_ (
    .A(selector),
    .B(lane0[25]),
    .Y(_095_)
  );
  NAND _246_ (
    .A(selector),
    .B(_028_),
    .Y(_096_)
  );
  NAND _247_ (
    .A(reset_L),
    .B(_096_),
    .Y(_097_)
  );
  NOR _248_ (
    .A(_095_),
    .B(_097_),
    .Y(_000_[25])
  );
  NOR _249_ (
    .A(selector),
    .B(lane0[26]),
    .Y(_098_)
  );
  NAND _250_ (
    .A(selector),
    .B(_029_),
    .Y(_099_)
  );
  NAND _251_ (
    .A(reset_L),
    .B(_099_),
    .Y(_100_)
  );
  NOR _252_ (
    .A(_098_),
    .B(_100_),
    .Y(_000_[26])
  );
  NOR _253_ (
    .A(selector),
    .B(lane0[27]),
    .Y(_101_)
  );
  NAND _254_ (
    .A(selector),
    .B(_030_),
    .Y(_102_)
  );
  NAND _255_ (
    .A(reset_L),
    .B(_102_),
    .Y(_103_)
  );
  NOR _256_ (
    .A(_101_),
    .B(_103_),
    .Y(_000_[27])
  );
  NOR _257_ (
    .A(selector),
    .B(lane0[28]),
    .Y(_104_)
  );
  NAND _258_ (
    .A(selector),
    .B(_031_),
    .Y(_105_)
  );
  NAND _259_ (
    .A(reset_L),
    .B(_105_),
    .Y(_106_)
  );
  NOR _260_ (
    .A(_104_),
    .B(_106_),
    .Y(_000_[28])
  );
  NOR _261_ (
    .A(selector),
    .B(lane0[29]),
    .Y(_107_)
  );
  NAND _262_ (
    .A(selector),
    .B(_032_),
    .Y(_108_)
  );
  NAND _263_ (
    .A(reset_L),
    .B(_108_),
    .Y(_109_)
  );
  NOR _264_ (
    .A(_107_),
    .B(_109_),
    .Y(_000_[29])
  );
  NOR _265_ (
    .A(selector),
    .B(lane0[30]),
    .Y(_110_)
  );
  NAND _266_ (
    .A(selector),
    .B(_033_),
    .Y(_111_)
  );
  NAND _267_ (
    .A(reset_L),
    .B(_111_),
    .Y(_112_)
  );
  NOR _268_ (
    .A(_110_),
    .B(_112_),
    .Y(_000_[30])
  );
  NOR _269_ (
    .A(selector),
    .B(lane0[31]),
    .Y(_113_)
  );
  NAND _270_ (
    .A(selector),
    .B(_034_),
    .Y(_114_)
  );
  NAND _271_ (
    .A(reset_L),
    .B(_114_),
    .Y(_115_)
  );
  NOR _272_ (
    .A(_113_),
    .B(_115_),
    .Y(_000_[31])
  );
  NOR _273_ (
    .A(lane0[0]),
    .B(selector),
    .Y(_116_)
  );
  NAND _274_ (
    .A(_003_),
    .B(selector),
    .Y(_117_)
  );
  NAND _275_ (
    .A(reset_L),
    .B(_117_),
    .Y(_118_)
  );
  NOR _276_ (
    .A(_116_),
    .B(_118_),
    .Y(_000_[0])
  );
  NOR _277_ (
    .A(selector),
    .B(lane0[1]),
    .Y(_119_)
  );
  NAND _278_ (
    .A(selector),
    .B(_004_),
    .Y(_120_)
  );
  NAND _279_ (
    .A(reset_L),
    .B(_120_),
    .Y(_121_)
  );
  NOR _280_ (
    .A(_119_),
    .B(_121_),
    .Y(_000_[1])
  );
  NOR _281_ (
    .A(selector),
    .B(lane0[2]),
    .Y(_122_)
  );
  NAND _282_ (
    .A(selector),
    .B(_005_),
    .Y(_123_)
  );
  NAND _283_ (
    .A(reset_L),
    .B(_123_),
    .Y(_124_)
  );
  NOR _284_ (
    .A(_122_),
    .B(_124_),
    .Y(_000_[2])
  );
  NOR _285_ (
    .A(selector),
    .B(lane0[3]),
    .Y(_125_)
  );
  NAND _286_ (
    .A(selector),
    .B(_006_),
    .Y(_126_)
  );
  NAND _287_ (
    .A(reset_L),
    .B(_126_),
    .Y(_127_)
  );
  NOR _288_ (
    .A(_125_),
    .B(_127_),
    .Y(_000_[3])
  );
  NOR _289_ (
    .A(selector),
    .B(lane0[4]),
    .Y(_128_)
  );
  NAND _290_ (
    .A(selector),
    .B(_007_),
    .Y(_129_)
  );
  NAND _291_ (
    .A(reset_L),
    .B(_129_),
    .Y(_130_)
  );
  NOR _292_ (
    .A(_128_),
    .B(_130_),
    .Y(_000_[4])
  );
  (* src = "synth.v:12" *)
  DFF _293_ (
    .C(clk_2f),
    .D(valid_1),
    .Q(valid_out)
  );
  (* src = "synth.v:12" *)
  DFF _294_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "synth.v:12" *)
  DFF _295_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "synth.v:12" *)
  DFF _296_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "synth.v:12" *)
  DFF _297_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "synth.v:12" *)
  DFF _298_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "synth.v:12" *)
  DFF _299_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "synth.v:12" *)
  DFF _300_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "synth.v:12" *)
  DFF _301_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "synth.v:12" *)
  DFF _302_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(data_out[8])
  );
  (* src = "synth.v:12" *)
  DFF _303_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(data_out[9])
  );
  (* src = "synth.v:12" *)
  DFF _304_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(data_out[10])
  );
  (* src = "synth.v:12" *)
  DFF _305_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(data_out[11])
  );
  (* src = "synth.v:12" *)
  DFF _306_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(data_out[12])
  );
  (* src = "synth.v:12" *)
  DFF _307_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(data_out[13])
  );
  (* src = "synth.v:12" *)
  DFF _308_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(data_out[14])
  );
  (* src = "synth.v:12" *)
  DFF _309_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(data_out[15])
  );
  (* src = "synth.v:12" *)
  DFF _310_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(data_out[16])
  );
  (* src = "synth.v:12" *)
  DFF _311_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(data_out[17])
  );
  (* src = "synth.v:12" *)
  DFF _312_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(data_out[18])
  );
  (* src = "synth.v:12" *)
  DFF _313_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(data_out[19])
  );
  (* src = "synth.v:12" *)
  DFF _314_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(data_out[20])
  );
  (* src = "synth.v:12" *)
  DFF _315_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(data_out[21])
  );
  (* src = "synth.v:12" *)
  DFF _316_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(data_out[22])
  );
  (* src = "synth.v:12" *)
  DFF _317_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(data_out[23])
  );
  (* src = "synth.v:12" *)
  DFF _318_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(data_out[24])
  );
  (* src = "synth.v:12" *)
  DFF _319_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(data_out[25])
  );
  (* src = "synth.v:12" *)
  DFF _320_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(data_out[26])
  );
  (* src = "synth.v:12" *)
  DFF _321_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(data_out[27])
  );
  (* src = "synth.v:12" *)
  DFF _322_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(data_out[28])
  );
  (* src = "synth.v:12" *)
  DFF _323_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(data_out[29])
  );
  (* src = "synth.v:12" *)
  DFF _324_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(data_out[30])
  );
  (* src = "synth.v:12" *)
  DFF _325_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(data_out[31])
  );
  (* src = "synth.v:12" *)
  DFF _326_ (
    .C(clk_2f),
    .D(_001_),
    .Q(selector)
  );
endmodule
