/* Generated by Yosys 0.9+4300 (git sha1 551ef85c, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "synth.v:1.1-57.10" *)
module synth(clk_4f, clk_32f, reset_L, data_in, valid_in, data_out);
  (* src = "synth.v:12.1-55.4" *)
  wire [2:0] _000_;
  (* src = "synth.v:12.1-55.4" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "synth.v:3.9-3.16" *)
  input clk_32f;
  (* src = "synth.v:2.9-2.15" *)
  input clk_4f;
  (* src = "synth.v:5.15-5.22" *)
  input [7:0] data_in;
  (* src = "synth.v:7.13-7.21" *)
  output data_out;
  (* src = "synth.v:4.9-4.16" *)
  input reset_L;
  (* init = 3'h0 *)
  (* src = "synth.v:9.12-9.20" *)
  wire [2:0] selector;
  (* src = "synth.v:10.12-10.19" *)
  wire [7:0] tmp_out;
  (* src = "synth.v:6.9-6.17" *)
  input valid_in;
  NOT _068_ (
    .A(reset_L),
    .Y(_020_)
  );
  NOT _069_ (
    .A(selector[0]),
    .Y(_000_[0])
  );
  NOT _070_ (
    .A(selector[1]),
    .Y(_027_)
  );
  NOT _071_ (
    .A(valid_in),
    .Y(_028_)
  );
  NOT _072_ (
    .A(data_in[0]),
    .Y(_029_)
  );
  NOT _073_ (
    .A(data_in[1]),
    .Y(_030_)
  );
  NOT _074_ (
    .A(data_in[2]),
    .Y(_031_)
  );
  NOT _075_ (
    .A(data_in[3]),
    .Y(_032_)
  );
  NOT _076_ (
    .A(data_in[4]),
    .Y(_033_)
  );
  NOT _077_ (
    .A(data_in[5]),
    .Y(_034_)
  );
  NOT _078_ (
    .A(data_in[6]),
    .Y(_035_)
  );
  NOT _079_ (
    .A(data_in[7]),
    .Y(_036_)
  );
  NOT _080_ (
    .A(tmp_out[5]),
    .Y(_037_)
  );
  NOT _081_ (
    .A(tmp_out[2]),
    .Y(_038_)
  );
  NOT _082_ (
    .A(tmp_out[0]),
    .Y(_039_)
  );
  NAND _083_ (
    .A(data_out),
    .B(_028_),
    .Y(_040_)
  );
  NAND _084_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_041_)
  );
  NOT _085_ (
    .A(_041_),
    .Y(_042_)
  );
  NAND _086_ (
    .A(tmp_out[4]),
    .B(_042_),
    .Y(_043_)
  );
  NAND _087_ (
    .A(_000_[0]),
    .B(selector[1]),
    .Y(_044_)
  );
  NOT _088_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _089_ (
    .A(_037_),
    .B(_044_),
    .Y(_046_)
  );
  NAND _090_ (
    .A(selector[0]),
    .B(_027_),
    .Y(_047_)
  );
  NOT _091_ (
    .A(_047_),
    .Y(_048_)
  );
  NAND _092_ (
    .A(tmp_out[6]),
    .B(_048_),
    .Y(_049_)
  );
  NOR _093_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_050_)
  );
  NAND _094_ (
    .A(tmp_out[7]),
    .B(_050_),
    .Y(_051_)
  );
  NAND _095_ (
    .A(_049_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _096_ (
    .A(selector[2]),
    .B(_046_),
    .Y(_053_)
  );
  NAND _097_ (
    .A(_043_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _098_ (
    .A(_052_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _099_ (
    .A(tmp_out[1]),
    .B(_045_),
    .Y(_056_)
  );
  NOR _100_ (
    .A(_038_),
    .B(_047_),
    .Y(_057_)
  );
  NAND _101_ (
    .A(tmp_out[3]),
    .B(_050_),
    .Y(_058_)
  );
  NOR _102_ (
    .A(_039_),
    .B(_041_),
    .Y(_059_)
  );
  NAND _103_ (
    .A(_056_),
    .B(_058_),
    .Y(_060_)
  );
  NOR _104_ (
    .A(_057_),
    .B(_059_),
    .Y(_061_)
  );
  NAND _105_ (
    .A(selector[2]),
    .B(_061_),
    .Y(_062_)
  );
  NOR _106_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _107_ (
    .A(_055_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _108_ (
    .A(valid_in),
    .B(_064_),
    .Y(_065_)
  );
  NAND _109_ (
    .A(_040_),
    .B(_065_),
    .Y(_022_)
  );
  NAND _110_ (
    .A(_044_),
    .B(_047_),
    .Y(_000_[1])
  );
  NAND _111_ (
    .A(selector[2]),
    .B(_041_),
    .Y(_066_)
  );
  NOR _112_ (
    .A(selector[2]),
    .B(_041_),
    .Y(_067_)
  );
  NOT _113_ (
    .A(_067_),
    .Y(_023_)
  );
  NAND _114_ (
    .A(_066_),
    .B(_023_),
    .Y(_000_[2])
  );
  NAND _115_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_024_)
  );
  NOT _116_ (
    .A(_024_),
    .Y(_001_[0])
  );
  NAND _117_ (
    .A(valid_in),
    .B(data_in[1]),
    .Y(_025_)
  );
  NOT _118_ (
    .A(_025_),
    .Y(_001_[1])
  );
  NAND _119_ (
    .A(valid_in),
    .B(_031_),
    .Y(_001_[2])
  );
  NAND _120_ (
    .A(valid_in),
    .B(_032_),
    .Y(_001_[3])
  );
  NAND _121_ (
    .A(valid_in),
    .B(_033_),
    .Y(_001_[4])
  );
  NAND _122_ (
    .A(valid_in),
    .B(_034_),
    .Y(_001_[5])
  );
  NAND _123_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_026_)
  );
  NOT _124_ (
    .A(_026_),
    .Y(_001_[6])
  );
  NAND _125_ (
    .A(valid_in),
    .B(_036_),
    .Y(_001_[7])
  );
  NOR _126_ (
    .A(reset_L),
    .B(_029_),
    .Y(_002_)
  );
  NOR _127_ (
    .A(reset_L),
    .B(_030_),
    .Y(_003_)
  );
  NOR _128_ (
    .A(reset_L),
    .B(_031_),
    .Y(_004_)
  );
  NOR _129_ (
    .A(reset_L),
    .B(_032_),
    .Y(_005_)
  );
  NOR _130_ (
    .A(reset_L),
    .B(_033_),
    .Y(_006_)
  );
  NOR _131_ (
    .A(reset_L),
    .B(_034_),
    .Y(_007_)
  );
  NOR _132_ (
    .A(reset_L),
    .B(_035_),
    .Y(_008_)
  );
  NOR _133_ (
    .A(reset_L),
    .B(_036_),
    .Y(_009_)
  );
  NOR _134_ (
    .A(reset_L),
    .B(data_in[0]),
    .Y(_010_)
  );
  NOR _135_ (
    .A(reset_L),
    .B(data_in[1]),
    .Y(_011_)
  );
  NOR _136_ (
    .A(reset_L),
    .B(data_in[2]),
    .Y(_012_)
  );
  NOR _137_ (
    .A(reset_L),
    .B(data_in[3]),
    .Y(_013_)
  );
  NOR _138_ (
    .A(reset_L),
    .B(data_in[4]),
    .Y(_014_)
  );
  NOR _139_ (
    .A(reset_L),
    .B(data_in[5]),
    .Y(_015_)
  );
  NOR _140_ (
    .A(reset_L),
    .B(data_in[6]),
    .Y(_016_)
  );
  NOR _141_ (
    .A(reset_L),
    .B(data_in[7]),
    .Y(_017_)
  );
  NOT _142_ (
    .A(reset_L),
    .Y(_019_)
  );
  NOT _143_ (
    .A(reset_L),
    .Y(_018_)
  );
  NOT _144_ (
    .A(reset_L),
    .Y(_021_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _145_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(tmp_out[0]),
    .R(_010_),
    .S(_002_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _146_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(tmp_out[1]),
    .R(_011_),
    .S(_003_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _147_ (
    .C(clk_32f),
    .D(_001_[2]),
    .Q(tmp_out[2]),
    .R(_012_),
    .S(_004_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _148_ (
    .C(clk_32f),
    .D(_001_[3]),
    .Q(tmp_out[3]),
    .R(_013_),
    .S(_005_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _149_ (
    .C(clk_32f),
    .D(_001_[4]),
    .Q(tmp_out[4]),
    .R(_014_),
    .S(_006_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _150_ (
    .C(clk_32f),
    .D(_001_[5]),
    .Q(tmp_out[5]),
    .R(_015_),
    .S(_007_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _151_ (
    .C(clk_32f),
    .D(_001_[6]),
    .Q(tmp_out[6]),
    .R(_016_),
    .S(_008_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _152_ (
    .C(clk_32f),
    .D(_001_[7]),
    .Q(tmp_out[7]),
    .R(_017_),
    .S(_009_)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _153_ (
    .C(clk_32f),
    .D(_000_[0]),
    .Q(selector[0]),
    .R(_018_),
    .S(1'h0)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _154_ (
    .C(clk_32f),
    .D(_000_[1]),
    .Q(selector[1]),
    .R(_019_),
    .S(1'h0)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _155_ (
    .C(clk_32f),
    .D(_000_[2]),
    .Q(selector[2]),
    .R(_020_),
    .S(1'h0)
  );
  (* src = "synth.v:12.1-55.4" *)
  DFFSR _156_ (
    .C(clk_32f),
    .D(_022_),
    .Q(data_out),
    .R(_021_),
    .S(1'h0)
  );
endmodule
