/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "conv_32b_to_8b_synth.v:1" *)
module conv_32b_to_8b_synth(data_in, clk, clk_4f, valid_in, data_out, valid_out);
  (* src = "conv_32b_to_8b_synth.v:7" *)
  wire [7:0] _000_;
  (* src = "conv_32b_to_8b_synth.v:7" *)
  wire [1:0] _001_;
  (* src = "conv_32b_to_8b_synth.v:7" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "conv_32b_to_8b_synth.v:2" *)
  input clk;
  (* src = "conv_32b_to_8b_synth.v:2" *)
  input clk_4f;
  (* src = "conv_32b_to_8b_synth.v:1" *)
  input [31:0] data_in;
  (* src = "conv_32b_to_8b_synth.v:3" *)
  output [7:0] data_out;
  (* src = "conv_32b_to_8b_synth.v:6" *)
  wire [1:0] sel;
  (* src = "conv_32b_to_8b_synth.v:2" *)
  input valid_in;
  (* src = "conv_32b_to_8b_synth.v:4" *)
  output valid_out;
  NOT _068_ (
    .A(sel[0]),
    .Y(_028_)
  );
  NOT _069_ (
    .A(sel[1]),
    .Y(_029_)
  );
  NOT _070_ (
    .A(valid_in),
    .Y(_030_)
  );
  NOR _071_ (
    .A(_028_),
    .B(_029_),
    .Y(_031_)
  );
  NAND _072_ (
    .A(sel[0]),
    .B(sel[1]),
    .Y(_032_)
  );
  NAND _073_ (
    .A(data_in[0]),
    .B(_031_),
    .Y(_033_)
  );
  NOR _074_ (
    .A(sel[0]),
    .B(sel[1]),
    .Y(_034_)
  );
  NAND _075_ (
    .A(data_in[24]),
    .B(_034_),
    .Y(_035_)
  );
  NAND _076_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _077_ (
    .A(sel[0]),
    .B(_029_),
    .Y(_037_)
  );
  NAND _078_ (
    .A(data_in[8]),
    .B(_037_),
    .Y(_038_)
  );
  NOR _079_ (
    .A(_028_),
    .B(sel[1]),
    .Y(_039_)
  );
  NAND _080_ (
    .A(data_in[16]),
    .B(_039_),
    .Y(_040_)
  );
  NAND _081_ (
    .A(_038_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _082_ (
    .A(_036_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _083_ (
    .A(_030_),
    .B(_042_),
    .Y(_000_[0])
  );
  NAND _084_ (
    .A(data_in[25]),
    .B(_034_),
    .Y(_043_)
  );
  NAND _085_ (
    .A(data_in[9]),
    .B(_037_),
    .Y(_044_)
  );
  NAND _086_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _087_ (
    .A(data_in[1]),
    .B(_031_),
    .Y(_046_)
  );
  NAND _088_ (
    .A(data_in[17]),
    .B(_039_),
    .Y(_047_)
  );
  NAND _089_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _090_ (
    .A(_045_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _091_ (
    .A(_030_),
    .B(_049_),
    .Y(_000_[1])
  );
  NAND _092_ (
    .A(data_in[2]),
    .B(_031_),
    .Y(_050_)
  );
  NAND _093_ (
    .A(data_in[26]),
    .B(_034_),
    .Y(_051_)
  );
  NAND _094_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _095_ (
    .A(data_in[10]),
    .B(_037_),
    .Y(_053_)
  );
  NAND _096_ (
    .A(data_in[18]),
    .B(_039_),
    .Y(_054_)
  );
  NAND _097_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _098_ (
    .A(_052_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _099_ (
    .A(_030_),
    .B(_056_),
    .Y(_000_[2])
  );
  NAND _100_ (
    .A(data_in[3]),
    .B(_031_),
    .Y(_057_)
  );
  NAND _101_ (
    .A(data_in[27]),
    .B(_034_),
    .Y(_058_)
  );
  NAND _102_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _103_ (
    .A(data_in[11]),
    .B(_037_),
    .Y(_060_)
  );
  NAND _104_ (
    .A(data_in[19]),
    .B(_039_),
    .Y(_061_)
  );
  NAND _105_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _106_ (
    .A(_059_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _107_ (
    .A(_030_),
    .B(_063_),
    .Y(_000_[3])
  );
  NAND _108_ (
    .A(data_in[4]),
    .B(_031_),
    .Y(_064_)
  );
  NAND _109_ (
    .A(data_in[28]),
    .B(_034_),
    .Y(_065_)
  );
  NAND _110_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _111_ (
    .A(data_in[12]),
    .B(_037_),
    .Y(_067_)
  );
  NAND _112_ (
    .A(data_in[20]),
    .B(_039_),
    .Y(_003_)
  );
  NAND _113_ (
    .A(_067_),
    .B(_003_),
    .Y(_004_)
  );
  NOR _114_ (
    .A(_066_),
    .B(_004_),
    .Y(_005_)
  );
  NOR _115_ (
    .A(_030_),
    .B(_005_),
    .Y(_000_[4])
  );
  NAND _116_ (
    .A(data_in[5]),
    .B(_031_),
    .Y(_006_)
  );
  NAND _117_ (
    .A(data_in[29]),
    .B(_034_),
    .Y(_007_)
  );
  NAND _118_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _119_ (
    .A(data_in[13]),
    .B(_037_),
    .Y(_009_)
  );
  NAND _120_ (
    .A(data_in[21]),
    .B(_039_),
    .Y(_010_)
  );
  NAND _121_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _122_ (
    .A(_008_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _123_ (
    .A(_030_),
    .B(_012_),
    .Y(_000_[5])
  );
  NAND _124_ (
    .A(data_in[6]),
    .B(_031_),
    .Y(_013_)
  );
  NAND _125_ (
    .A(data_in[30]),
    .B(_034_),
    .Y(_014_)
  );
  NAND _126_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _127_ (
    .A(data_in[14]),
    .B(_037_),
    .Y(_016_)
  );
  NAND _128_ (
    .A(data_in[22]),
    .B(_039_),
    .Y(_017_)
  );
  NAND _129_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _130_ (
    .A(_015_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _131_ (
    .A(_030_),
    .B(_019_),
    .Y(_000_[6])
  );
  NAND _132_ (
    .A(data_in[7]),
    .B(_031_),
    .Y(_020_)
  );
  NAND _133_ (
    .A(data_in[31]),
    .B(_034_),
    .Y(_021_)
  );
  NAND _134_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _135_ (
    .A(data_in[15]),
    .B(_037_),
    .Y(_023_)
  );
  NAND _136_ (
    .A(data_in[23]),
    .B(_039_),
    .Y(_024_)
  );
  NAND _137_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _138_ (
    .A(_022_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _139_ (
    .A(_030_),
    .B(_026_),
    .Y(_000_[7])
  );
  NOR _140_ (
    .A(sel[0]),
    .B(_030_),
    .Y(_001_[0])
  );
  NAND _141_ (
    .A(valid_in),
    .B(_032_),
    .Y(_027_)
  );
  NOR _142_ (
    .A(_034_),
    .B(_027_),
    .Y(_001_[1])
  );
  BUF _143_ (
    .A(valid_in),
    .Y(_002_)
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _144_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(sel[0])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _145_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(sel[1])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _146_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _147_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _148_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _149_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _150_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _151_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _152_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _153_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "conv_32b_to_8b_synth.v:7" *)
  DFF _154_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_out)
  );
endmodule
