/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "estructural.v:1" *)
module estructural(data_input, valid_out, clk_32f, clk_4f, active_output, data_output, BC_contador);
  (* src = "estructural.v:8" *)
  output [2:0] BC_contador;
  (* src = "estructural.v:6" *)
  output active_output;
  (* src = "estructural.v:10" *)
  wire [0:7] bus_0;
  (* src = "estructural.v:4" *)
  input clk_32f;
  (* src = "estructural.v:5" *)
  input clk_4f;
  (* src = "estructural.v:11" *)
  wire [2:0] contador;
  (* src = "estructural.v:2" *)
  input data_input;
  (* src = "estructural.v:7" *)
  output [7:0] data_output;
  (* src = "estructural.v:3" *)
  input valid_out;
  (* src = "estructural.v:47" *)
  DFF _0_ (
    .C(clk_4f),
    .D(bus_0[7]),
    .Q(data_output[0])
  );
  (* src = "estructural.v:47" *)
  DFF _1_ (
    .C(clk_4f),
    .D(bus_0[6]),
    .Q(data_output[1])
  );
  (* src = "estructural.v:47" *)
  DFF _2_ (
    .C(clk_4f),
    .D(bus_0[5]),
    .Q(data_output[2])
  );
  (* src = "estructural.v:47" *)
  DFF _3_ (
    .C(clk_4f),
    .D(bus_0[4]),
    .Q(data_output[3])
  );
  (* src = "estructural.v:47" *)
  DFF _4_ (
    .C(clk_4f),
    .D(bus_0[3]),
    .Q(data_output[4])
  );
  (* src = "estructural.v:47" *)
  DFF _5_ (
    .C(clk_4f),
    .D(bus_0[2]),
    .Q(data_output[5])
  );
  (* src = "estructural.v:47" *)
  DFF _6_ (
    .C(clk_4f),
    .D(bus_0[1]),
    .Q(data_output[6])
  );
  (* src = "estructural.v:47" *)
  DFF _7_ (
    .C(clk_4f),
    .D(bus_0[0]),
    .Q(data_output[7])
  );
  (* src = "estructural.v:17" *)
  DFF _8_ (
    .C(clk_32f),
    .D(data_input),
    .Q(bus_0[0])
  );
  assign BC_contador = 3'h0;
  assign active_output = 1'h0;
  assign contador = 3'h0;
endmodule
